import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Berliner-Shopping',
  description: 'Generated by Dark dEvelopers:)',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
